name: ex-generator

on:
 push:
   branches: [ master ]

jobs:
 build:
   name: Build ex-generator
   runs-on: ubuntu-latest

   strategy:
     matrix:
       node-version: [12.x]

   steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       id: Build
       uses: actions/setup-node@v2-beta
       with:
         node-version: ${{ matrix.node-version }}
     - run: npm ci
     - run: npm run build --if-present
     - uses: act10ns/slack@v1
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       with:
         status: ${{ job.status }}
         steps: ${{ toJson(steps) }}
       if: always()


 deploy:
   name: Deploy ex-discussion - Cloud Function
   runs-on: ubuntu-latest
   needs: [build]
   steps:
     - uses: actions/checkout@v2

     - name: Create variables.yaml
       id: Create-Environment-Variables
       uses: microsoft/variable-substitution@v1
       with:
         files: 'variables.yaml'
       env:
         GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
         ENVIRONMENT: 'production'

     - name: Deploy to GCP
       id: Deploy
       uses: actions-hub/gcloud@318.0.0
       env:
         PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
         APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_CREDENTIALS}}
       with:
         args: functions deploy content-generator --region europe-west2 --source ./ --runtime nodejs12 --entry-point generate --env-vars-file variables.yaml --trigger-http --allow-unauthenticated

     - uses: act10ns/slack@v1
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       with:
         status: ${{ job.status }}
         steps: ${{ toJson(steps) }}
       if: always()
